# Description of the Following Variables:

encounter_id, patient_nbr, race, gender, age, weight, admission_type_id, charge_disposition_id, admission_source_id

# Get Basic Details.

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


df = pd.read_csv('https://raw.githubusercontent.com/eshentong/BA780-team10-project/main/readmission.csv')

# Get basic statistics of the dataset
df.describe()

encounter_id   patient_nbr  admission_type_id  \
count  1.017660e+05  1.017660e+05      101766.000000   
mean   1.652016e+08  5.433040e+07           2.024006   
std    1.026403e+08  3.869636e+07           1.445403   
min    1.252200e+04  1.350000e+02           1.000000   
25%    8.496119e+07  2.341322e+07           1.000000   
50%    1.523890e+08  4.550514e+07           1.000000   
75%    2.302709e+08  8.754595e+07           3.000000   
max    4.438672e+08  1.895026e+08           8.000000   

       discharge_disposition_id  admission_source_id  time_in_hospital  \
count             101766.000000        101766.000000     101766.000000   
mean                   3.715642             5.754437          4.395987   
std                    5.280166             4.064081          2.985108   
min                    1.000000             1.000000          1.000000   
25%                    1.000000             1.000000          2.000000   
50%                    1.000000             7.000000          4.000000   
75%                    4.000000             7.000000          6.000000   
max                   28.000000            25.000000         14.000000   

       num_lab_procedures  num_procedures  num_medications  number_outpatient  \
count       101766.000000   101766.000000    101766.000000      101766.000000   
mean            43.095641        1.339730        16.021844           0.369357   
std             19.674362        1.705807         8.127566           1.267265   
min              1.000000        0.000000         1.000000           0.000000   
25%             31.000000        0.000000        10.000000           0.000000   
50%             44.000000        1.000000        15.000000           0.000000   
75%             57.000000        2.000000        20.000000           0.000000   
max            132.000000        6.000000        81.000000          42.000000   

       number_emergency  number_inpatient  number_diagnoses  
count     101766.000000     101766.000000     101766.000000  
mean           0.197836          0.635566          7.422607  
std            0.930472          1.262863          1.933600  
min            0.000000          0.000000          1.000000  
25%            0.000000          0.000000          6.000000  
50%            0.000000          0.000000          8.000000  
75%            0.000000          1.000000          9.000000  
max           76.000000         21.000000         16.000000

In [4]:
# Display the first few rows.
df.head()


encounter_id  patient_nbr             race  gender      age weight  \
0       2278392      8222157        Caucasian  Female   [0-10)      ?   
1        149190     55629189        Caucasian  Female  [10-20)      ?   
2         64410     86047875  AfricanAmerican  Female  [20-30)      ?   
3        500364     82442376        Caucasian    Male  [30-40)      ?   
4         16680     42519267        Caucasian    Male  [40-50)      ?   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   
1                  1                         1                    7   
2                  1                         1                    7   
3                  1                         1                    7   
4                  1                         1                    7   

   time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                 1  ...          No      No                   No   
1                 3  ...          No      Up                   No   
2                 2  ...          No      No                   No   
3                 2  ...          No      Up                   No   
4                 1  ...          No  Steady                   No   

   glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
0                   No                        No                       No   
1                   No                        No                       No   
2                   No                        No                       No   
3                   No                        No                       No   
4                   No                        No                       No   

   metformin-pioglitazone  change diabetesMed readmitted  
0                      No      No          No         NO  
1                      No      Ch         Yes        >30  
2                      No      No         Yes         NO  
3                      No      Ch         Yes         NO  
4                      No      Ch         Yes         NO  

[5 rows x 50 columns]

In [5]:
# Creating a copy of DataFrame 'df' and assigning it to a new variable df_clean.
df_clean = df.copy()


# encounter_id : A unique identifier for a patient visit.
*   No missing values
*   Ready to use





# patient_nbr : Unique identfier of a patient.

*   No missing values
*   Repititions as per the number of encounters by patient
*   Ready to use



# race : Values Caucasian, Asian, African American, Hispanic and other.


*   Missing data - 2%
*   Action - Dropping the rows.

In [17]:
# Display all unique values

df['race'].unique()


array(['Caucasian', 'AfricanAmerican', '?', 'Other', 'Asian', 'Hispanic'],
      dtype=object)

# gender : Values - Male, Female and Unknown/Invalid

*   3 rows with missing data
*   Action - Dropping the rows

In [16]:
# Display all unique values

df['gender'].unique()

array(['Female', 'Male', 'Unknown/Invalid'], dtype=object)

In [15]:
# dropping the rows with 'Unknown/Invalid'
df_clean = df_clean[df_clean['race'] != 'Unknown/Invalid']

# age : Grouped in 10 - year intervals [0,10), [10-20)....,[90-100)



*   No missing data
*   Ready to use



# weight :


*   Contains 97% of the missing datList item
*   Action: Dropping the column

In [9]:
# Drop 'weight' column
df_clean.drop('weight',axis=1,inplace=True)

# admission_type_id : Numerical codes representing 9 different values, example - emergency, urgent, elective, new born and not available.


*   No Data missing
*   Ready to use



In [20]:
df['admission_type_id'].unique()

array([6, 1, 2, 3, 4, 5, 8, 7])

# discharge_disposition_id : Numerical codes representing 29 different values, like discharged to home, expired and not available.

In [19]:
df['discharge_disposition_id'].unique()

array([25,  1,  3,  6,  2,  5, 11,  7, 10,  4, 14, 18,  8, 13, 12, 16, 17,
       22, 23,  9, 20, 15, 24, 28, 19, 27])

# admission_source_id : Contains values for example physician referral, admission room, and transfer from an hospital.


*   No missing data
*   Ready to use



In [18]:
df['admission_source_id'].unique()

array([ 1,  7,  2,  4,  5,  6, 20,  3, 17,  8,  9, 14, 10, 22, 11, 25, 13])